### ISSUE TITLE
Can't connect the pulsar server when run the connect on another server

### ISSUE THREAD

**Issue by sunlc210** [streamnative/pulsar-io-kafka#21]
When run the connector on another server but the broker ,config this 

  copy_kafka_schema: false

    # The properties to configure Pulsar client
    client:
      serviceUrl: "pulsar://10.2.51.154:6650"

    # The properties to configure Pulsar producer
    producer:

run it ,will throw below exception

Caused by: java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: syscall:getsockopt(..) failed: Connection refused: localhost/127.0.0.1:6650
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_111]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_111]
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647) ~[?:1.8.0_111]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_111]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_111]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[?:1.8.0_111]
        at org.apache.pulsar.client.impl.ConnectionPool.lambda$connectToAddress$17(ConnectionPool.java:275) ~[org.apache.pulsar-pulsar-client-original-2.4.0.jar:2.4.0]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]

**Comment by jiazhai** [comment]
@tuteng to take a look
